name: "Deploy using kustomize"
description: "Deploy using kustomize to AWS S3"
inputs:
  secrets:
    required: true
    description: "The aws-access-key-id used to authenticate with AWS"
  aws-secret-access-key:
    required: true
    description: "The aws-secret-access-key used to authenticate with AWS"
  aws-cluster-name:
    required: true
    description: "The cluster where we want to deploy the app"
  aws-region:
    required: true
    description: "The region of the cluster"
  path:
    required: false
    description: "the path of your manifest files"
    default: .  
    
runs:
  using: "composite"
  steps:
  - name: Set up AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      # Actions can't access to secrets so i pass them in as inputs
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}
  - name: update kube config
    shell: bash
    run: aws eks update-kubeconfig --name ${{ inputs.aws-cluster-name }} --region ${{ inputs.aws-region }}
  - name: Install kustomize
    shell: bash
    run: |
      curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      sudo mv kustomize /usr/local/bin/

  - name: Create Secret file
    env:
      SECRETS: '${{ inputs.secrets }}'
    shell: bash
    working-directory: ./k8s
    run: |
      for secret in $(echo "$SECRETS" | jq -r 'keys[]'); do
        value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS")"
        echo "$secret=$value" >> secret.env
      done
      
  - name: Kustomize build & apply
    shell: bash
    working-directory: ./k8s
    run: |
      kustomize build . | kubectl delete -f - || true
      sleep 2
      kustomize build . | kubectl apply -f -