
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-retain-sc  #We suppose this storage is already created (CICD)
  resources:
    requests:
      storage: 10Gi

